[versions]
agp = "8.13.0"
kotlin = "2.1.20"
coreKtx = "1.16.0"
junit = "4.13.2"
lifecycleRuntimeKtx = "2.8.7"
ksp = "2.1.20-1.0.32"
dagger = "2.56"
googleMaterial = "1.12.0"
appcompat = "1.7.0"
googleServices = "4.4.2"
firebaseCrashlytics = "3.0.3"
navigation = "2.8.9"
databinding = "8.9.1"
coroutinesAndroid = "1.10.1"
intuitSdp = "1.1.1"
swiperefreshlayoutVer = "1.1.0"
picassoVer = "2.71828"
retrofit2 = "2.11.0"
okhttp3 = "4.12.0"
gson = "2.12.1"
preference = "1.2.1"
coil = "2.7.0"
datastorepreferences = "1.1.4"
compressor = "3.0.1"
lottie = "6.6.2"
flexbox = "3.0.0"
chucker = "4.0.0"
stfalconImageViewer = "v1.0.1"
paging = "3.3.6"
jsoup = "1.17.2"
room = "2.7.0"
workRuntime = "2.10.0"
ccp = "2.7.0"
mukeshOtpView = "1.0.0"
media3 = "1.6.1"
photoView = "2.2.0"
ratingBar = "1.0.6"
materialratingbar = "1.4.0"
timelineview = "1.1.5"
razorpay = "1.6.37"
playservicesauth = "21.3.0"
playserviceslocation = "21.3.0"
playservicesmaps = "19.2.0"
firebaseBom = "33.12.0"
glide = "4.16.0"

signature = "1.3.1"
rackMonthPicker = "1.6.1"
koinCore = "4.1.0"
koinAndroid = "4.1.0"
koinAndroidxCompose = "4.0.2"

#androidPlayCore = "1.8.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

navigationfragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigationui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

databindingktx = { module = "androidx.databinding:databinding-ktx", version.ref = "databinding" }
databindingruntime = { module = "androidx.databinding:databinding-runtime", version.ref = "databinding" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesAndroid" }

sdp = { module = "com.intuit.sdp:sdp-android", version.ref = "intuitSdp" }
ssp = { module = "com.intuit.ssp:ssp-android", version.ref = "intuitSdp" }

swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayoutVer" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picassoVer" }

retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }
retrofit2-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit2" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }

#androidPlayCore = { module = "com.google.android.play:core-ktx", version.ref = "androidPlayCore" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }

datastorepreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorepreferences" }
datastorepreferencescore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorepreferences" }

compressor = { module = "id.zelory:compressor", version.ref = "compressor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }

chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

stfalconImageViewer = { module = "com.github.stfalcon-studio:StfalconImageViewer", version.ref = "stfalconImageViewer" }

paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "paging" }
paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
#noinspection SimilarGradleDependency
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
#noinspection SimilarGradleDependency
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
#noinspection SimilarGradleDependency
room-compiler-ksp = { module = "androidx.room:room-compiler", version.ref = "room" }
#noinspection SimilarGradleDependency
room-ktx-ksp = { module = "androidx.room:room-ktx", version.ref = "room" }

work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntime" }
ccp = { module = "com.hbb20:ccp", version.ref = "ccp" }
mukeshOtpView = { module = "com.github.rajputmukesh748:MukeshOtpView", version.ref = "mukeshOtpView" }

media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
#media3ExoplayerHls = { group = "androidx.media3", name = "media3-exoplayer-hl", version.ref = "media3" }

photoViews = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoView" }
ratingBar = { module = "com.github.fuzz-productions:RatingBar", version.ref = "ratingBar" }

materialratingbar = { module = "me.zhanghai.android.materialratingbar:library", version.ref = "materialratingbar" }
timelineview = { module = "com.github.vipulasri:timelineview", version.ref = "timelineview" }
razorpay = { module = "com.razorpay:checkout", version.ref = "razorpay" }

play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playservicesauth" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playserviceslocation" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playservicesmaps" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx" }
firebase-dynamic-links-ktx = { module = "com.google.firebase:firebase-dynamic-links-ktx" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
glideokhttp3 = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
signature = { module = "com.github.gcacace:signature-pad", version.ref = "signature" }
rackMonthPicker = { module = "com.github.kal72:RackMonthPicker", version.ref = "rackMonthPicker" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koinCore" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koinAndroid" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koinAndroidxCompose" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlin"  }
googleservices = { id = "com.google.gms.google-services",  version.ref = "googleServices"  }
firebasecrashlytics = { id = "com.google.firebase.crashlytics",  version.ref = "firebaseCrashlytics"  }